apiVersion: v1
kind: Pod
metadata:
  name: app-pod
spec:
   containers:
     - name: app
       image: nginx
       volumeMounts:
         - mountPath: "/usr/share/nginx/html"
           name: data-volume
   volumes:
     - name: data-volume
       persistentVolumeClaim:
         claimName: pvc-demo
