apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myreplica
  namespace: default
spec:
 replicas: 4
 selector:
  matchExpressions:
   - key: app
     operator: In
     values:
       - web
       - api
 template:
  metadata:
    labels:
      app: web
  spec:
    containers:
     - name: container1
       image: httpd:latest
       ports:
        - containerPort: 80
